### ISSUE TITLE
Failure to call `mix ua_inspector.download.databases`

### ISSUE THREAD

**Issue by rodrigues** [elixytics/ua_inspector#12]
I was trying to update from `0.14.0` to `0.16.0`, when I noticed the download task fails:

<img width="1849" alt="mix-download-fail" src="https://user-images.githubusercontent.com/128147/35060766-ab33561c-fbbf-11e7-8046-95cc515485ca.png">

It also did fail in `0.15.0`, same error.

Elixir `1.5.3`, OTP `20.2.2`

**Comment by mneudert** [comment]
Are you by any chance using MacOS?

I think the problem might be related to the internal module name change (uppercasing the `A` for naming consistency). As MacOS is case insensitive it might not have updated that change on your system.

Can you check if simply deleting your `_build` directory fixes the problem?

**Comment by mneudert** [comment]
Hm, forget what I said :D

The module naming is actually broken since that change. I will patch it and release a fix version on hex :)

**Comment by mneudert** [comment]
Done! Both `0.15.1` and `0.16.1` should behave as expected. Thank you for making me aware of this!

**Comment by rodrigues** [comment]
thanks @mneudert!

would be cool also to [retire](https://hex.pm/docs/tasks#hex_retire) these bad packages 👍🏼
