### ISSUE TITLE
Failed to load short code map

### ISSUE THREAD

**Issue by Slavenin** [elixytics/ua_inspector#14]
Hi!
After install lib:

> mix ua_inspector.download.databases
> UAInspector Database Download
> Download path: /opt/ua_database
> This command will overwrite any existing files!
> Really download? [Yn] y
> Download complete!

But when i run `mix phx.server`:

> [info] failed to load short code map: /opt/ua_database/short_codes.client_browsers.yml
> [info] failed to load short code map: /opt/ua_database/short_codes.device_brands.yml
> [info] failed to load short code map: /opt/ua_database/short_codes.mobile_browsers.yml
> [info] failed to load short code map: /opt/ua_database/short_codes.oss.yml

**Comment by mneudert** [comment]
I think you forgot the second download task required for those files. I have to admit the README is a bit unexpressive at that point and the "combined download task" is not yet in a hex release.

Can you try running `mix ua_inspector.download.short_code_maps` to see if that fixes your problem?

**Comment by Slavenin** [comment]
Yes. This work. But why in docs no this?

**Comment by mneudert** [comment]
It is stated in the documentation: https://hexdocs.pm/ua_inspector/readme.html#parser-databases

But probably not in a really good way for easy reading. The next release will get some cleanup using a combined download task and more polished documentation.

**Comment by Slavenin** [comment]
I see on github,  not on hexdocs.

> The next release will get some cleanup using a combined download task and more polished documentation.

ok. Tnx!
