### ISSUE TITLE
1.2.0 can't download in environments that don't have external services available

### ISSUE THREAD

**Issue by doughsay** [elixytics/ua_inspector#19]
The download task fails if the Elixir application can't fully start when using ua_inspector 1.2.0.

If the Elixir application depends on external services to boot (for example a postgres database), and the database is not reachable, then the download task fails.

This appears to be a new requirement in 1.2.0, as in 1.1.0 this didn't happen.

This breaks my build process because it involves building docker images.  The docker image runs `mix ua_inspector.download` during build, but allows no external connections, therefore the application fails to boot and the build fails.

**Comment by mneudert** [comment]
Can you try if running the download without the mix task fixes your problem?

```shell
mix run --no-start -e "UAInspector.Downloader.download()"
```

Depending on your configuration this should work without starting any applications. Until there is a fix to have a configuration of "applications required for the mix task to work" in place instead of just starting everything.

**Comment by mneudert** [comment]
I think I have a fix that does not require any configuration changes but this time it should get some proper verification before breaking other things: https://github.com/elixir-inspector/ua_inspector/tree/v1.2

This should only try to load the code required for the initializer modules without starting the complete application. Can you verify this is the case?

/ping @smaximov it would be great if you could also test this as it might affect you and I do no longer trust my simple local test app for this stuff :)

**Comment by smaximov** [comment]
@mneudert, 9ac280b1992cb62cb8d21011d1dbd1b203e4d9d4 works for me.

**Comment by doughsay** [comment]
@mneudert thanks for jumping on this so quickly!

Unfortunately, https://github.com/elixir-inspector/ua_inspector/commit/9ac280b1992cb62cb8d21011d1dbd1b203e4d9d4 still starts my entire umbrella application.

On the other hand, manually running the download function does work for me for now.  I will change my dockerfile build script to use that for now.

Thanks!

**Comment by mneudert** [comment]
Closing as this should be no issue anymore since release `v2.0.0`. I just missed mentioning it outside of the Changelog :sweat_smile:
