### ISSUE TITLE
Help adding Container Runtime User-Agents

### ISSUE THREAD

**Issue by josegomezr** [elixytics/ua_inspector#29]
I'd like to contribute some new regexes so `ua_inspector` can detect container runtimes (docker, buildah, and friends).

My journey started on Plausible, and now I'm pointed to this repo (see plausible/analytics#2078),

How can I contribute the new regexes?

**Comment by mneudert** [comment]
The next (and final) part of your journey is [matomo-org/device-detector](https://github.com/matomo-org/device-detector) where the regex sources are fetched from.

I would suggest to open an issue there (ideally with full example agents). If you want to try a pull request yourself I think the appropriate places would be [`regexes/client/libraries.yml`](https://github.com/matomo-org/device-detector/blob/6.0.2/regexes/client/libraries.yml) for the regexes and [`Tests/Parser/Client/fixtures/library.yml`](https://github.com/matomo-org/device-detector/blob/6.0.2/Tests/Parser/Client/fixtures/library.yml) for the test agents.

**Comment by josegomezr** [comment]
Thanks @mneudert ! Will continue my way upstream! :mage:

**Comment by josegomezr** [comment]
went though and it's merged! :partying_face: may I ask, when is the next release so the changes upstream are reflected here too?

**Comment by mneudert** [comment]
Next release will be done once I untangled my current mess of integrating the client hints into all the required places without going insane or trying to rewrite everything before a working release is available :grimacing:

**Comment by josegomezr** [comment]
Good luck then!

If you want an extra pair of completely Elixir-ignorant-yet-very-enthusiastic refactoring hands. Lmk!
