### ISSUE TITLE
Error downloading DBs on Heroku

### ISSUE THREAD

**Issue by madshargreave** [elixytics/ua_inspector#3]
Hi

I am deploying my application and trying to download the databases, but I receive the following error

```
~ $ heroku run bash
~ $ mix ua_inspector.download.databases
UAInspector Database Download
Download path: /app/.mix/ua_inspector
This command will overwrite any existing files!
Really download? [Yn] Y
** (File.CopyError) could not copy from /tmp/build_c58698da94639263d9c49d03de9af79d/deps/ua_inspector/lib/mix/ua_inspector/../files/README.md to /app/.mix/ua_inspector/README.md: no such file or directory
    (elixir) lib/file.ex:447: File.copy!/3
    lib/mix/ua_inspector/download.ex:53: Mix.UAInspector.Download.document_database_path/0
    lib/mix/ua_inspector/download/databases.ex:37: Mix.UAInspector.Download.Databases.run_confirmed/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by mneudert** [comment]
Hm... as it fails on the copy the permissions for the app directory should be ok. The download path should have been successfully created, right?

Could it be that the file it tries to copy has not been deployed?

**Comment by madshargreave** [comment]
I'm not sure

When using the UIInspector in production however, it returns unknown for all field, which also happened in dev when the database hadn't been loaded

**Comment by mneudert** [comment]
Yeah, if copying the file from your temp dir fails it won't download anything. Probably worth it to look if it is on the path mentioned in the stacktrace or maybe hasn't been copied.

Or you could just take a database downloaded from where it works and put it to the configured folder. And then skip the task altogether. Could become interesting once I finally get around to have some auto-download/-update/-reload logic in, but in the meantime it might be a solution.

**Comment by mneudert** [comment]
I patched together a potential fix for you in the branch [inline-download-readme](https://github.com/elixytics/ua_inspector/tree/inline-download-readme). The file it tries to copy is now inlined during compilation and then only written. That should prevent any problems with releases where the file might not be included.

Could you give it a shot and find out if that solves your problem?

**Comment by mneudert** [comment]
Just merged above mentioned branch into master. If you still get any issues downloading please add a comment here or open a new issue.
